import operator
from math import log
import time


def createDataSet():
    dataSet = [['age40', 'M', 'YES', 'NO', 'YES'],
               ['age50', 'F', 'NO', 'NO', 'NO'],
               ['age50', 'F', 'NO', 'NO', 'NO'],
               ['age30', 'M', 'YES', 'YES', 'NO'],
               ['age50', 'F', 'NO', 'NO', 'NO'],
               ['age40', 'F', 'NO', 'NO', 'NO'],
               ['age30', 'M', 'NO', 'NO', 'YES'],
               ['age30', 'M', 'YES', 'NO', 'YES'],
               ['age30', 'M', 'NO', 'YES', 'NO'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age50', 'M', 'YES', 'YES', 'NO'],
               ['age50', 'M', 'NO', 'NO', 'NO'],
               ['age30', 'M', 'NO', 'NO', 'YES'],
               ['age30', 'M', 'YES', 'NO', 'NO'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age50', 'F', 'NO', 'NO', 'NO'],
               ['age50', 'M', 'NO', 'NO', 'YES'],
               ['age30', 'M', 'YES', 'YES', 'YES'],
               ['age50', 'M', 'NO', 'YES', 'NO'],
               ['age30', 'M', 'YES', 'NO', 'YES'],
               ['age30', 'M', 'YES', 'NO', 'NO'],
               ['age30', 'M', 'YES', 'YES', 'NO'],
               ['age50', 'M', 'YES', 'NO', 'NO'],
               ['age30', 'M', 'YES', 'YES', 'NO'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age30', 'M', 'YES', 'YES', 'YES'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age30', 'M', 'YES', 'YES', 'NO'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age40', 'M', 'YES', 'NO', 'NO'],
               ['age50', 'M', 'NO', 'YES', 'NO'],
               ['age50', 'M', 'YES', 'NO', 'NO'],
               ['age40', 'M', 'YES', 'YES', 'YES'],
               ['age50', 'F', 'NO', 'NO', 'YES'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age40', 'F', 'NO', 'NO', 'NO'],
               ['age40', 'M', 'YES', 'NO', 'YES'],
               ['age30', 'M', 'YES', 'YES', 'NO'],
               ['age40', 'M', 'YES', 'YES', 'NO'],
               ['age50', 'M', 'YES', 'NO', 'NO'],
               ['age40', 'M', 'NO', 'NO', 'NO'],
               ['age40', 'M', 'YES', 'NO', 'YES'],
               ['age50', 'F', 'YES', 'YES', 'YES'],
               ['age40', 'M', 'NO', 'YES', 'NO'],
               ['age40', 'M', 'NO', 'NO', 'NO'],
               ['age40', 'M', 'YES', 'NO', 'YES'],
               ['age40', 'M', 'YES', 'NO', 'NO'],
               ['age40', 'M', 'YES', 'YES', 'YES'],
               ['age40', 'M', 'NO', 'YES', 'NO'],
               ['age40', 'M', 'YES', 'YES', 'NO'],
               ['age50', 'M', 'YES', 'NO', 'YES'],
               ['age40', 'M', 'NO', 'NO', 'NO'],
               ['age40', 'M', 'YES', 'YES', 'YES'],
               ['age50', 'M', 'NO', 'NO', 'NO'],
               ['age40', 'M', 'YES', 'YES', 'NO'],
               ['age50', 'M', 'YES', 'NO', 'YES'],
               ['age40', 'M', 'YES', 'YES', 'NO'],
               ['age30', 'M', 'YES', 'YES', 'NO'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age30', 'M', 'NO', 'YES', 'NO'],
               ['age50', 'F', 'NO', 'NO', 'NO'],
               ['age30', 'M', 'NO', 'YES', 'YES'],
               ['age40', 'F', 'NO', 'NO', 'YES'],
               ['age50', 'M', 'YES', 'YES', 'NO'],
               ['age30', 'M', 'YES', 'YES', 'YES'],
               ['age40', 'F', 'NO', 'NO', 'NO'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age30', 'M', 'YES', 'YES', 'NO'],
               ['age40', 'F', 'NO', 'NO', 'YES'],
               ['age40', 'F', 'NO', 'NO', 'NO'],
               ['age40', 'F', 'NO', 'NO', 'NO'],
               ['age40', 'F', 'YES', 'NO', 'NO'],
               ['age30', 'M', 'YES', 'NO', 'YES'],
               ['age40', 'F', 'YES', 'YES', 'YES'],
               ['age30', 'F', 'YES', 'NO', 'NO'],
               ['age30', 'M', 'YES', 'NO', 'NO'],
               ['age30', 'M', 'NO', 'NO', 'NO'],
               ['age40', 'M', 'YES', 'YES', 'NO'],
               ['age30', 'M', 'YES', 'YES', 'YES'],
               ['age30', 'M', 'YES', 'YES', 'YES'],
               ['age30', 'F', 'YES', 'NO', 'NO'],
               ['age40', 'F', 'NO', 'NO', 'NO'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age30', 'M', 'YES', 'YES', 'YES'],
               ['age40', 'F', 'NO', 'NO', 'NO'],
               ['age40', 'F', 'YES', 'NO', 'YES'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age40', 'M', 'YES', 'YES', 'YES'],
               ['age40', 'M', 'YES', 'YES', 'YES'],
               ['age30', 'M', 'YES', 'YES', 'NO'],
               ['age30', 'M', 'YES', 'NO', 'NO'],
               ['age30', 'M', 'NO', 'NO', 'NO'],
               ['age40', 'M', 'YES', 'YES', 'YES'],
               ['age40', 'M', 'YES', 'YES', 'YES'],
               ['age50', 'F', 'YES', 'NO', 'YES'],
               ['age30', 'F', 'NO', 'NO', 'YES'],
               ['age50', 'F', 'NO', 'NO', 'YES'],
               ['age30', 'M', 'NO', 'NO', 'NO'],
               ['age40', 'M', 'YES', 'YES', 'YES'],
               ['age40', 'F', 'NO', 'NO', 'NO'],
               ['age40', 'M', 'YES', 'NO', 'YES'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age30', 'M', 'YES', 'YES', 'YES'],
               ['age50', 'M', 'YES', 'YES', 'NO'],
               ['age50', 'M', 'YES', 'YES', 'NO'],
               ['age40', 'F', 'YES', 'NO', 'NO'],
               ['age50', 'F', 'NO', 'NO', 'NO'],
               ['age50', 'F', 'YES', 'NO', 'NO'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age30', 'M', 'NO', 'NO', 'NO'],
               ['age40', 'M', 'YES', 'YES', 'YES'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age40', 'M', 'YES', 'YES', 'NO'],
               ['age40', 'M', 'YES', 'NO', 'NO'],
               ['age40', 'M', 'YES', 'NO', 'NO'],
               ['age40', 'M', 'YES', 'NO', 'NO'],
               ['age40', 'M', 'YES', 'YES', 'NO'],
               ['age40', 'M', 'YES', 'YES', 'YES'],
               ['age40', 'M', 'YES', 'NO', 'NO'],
               ['age50', 'M', 'NO', 'YES', 'NO'],
               ['age40', 'M', 'NO', 'YES', 'YES'],
               ['age40', 'M', 'NO', 'NO', 'YES'],
               ['age40', 'M', 'YES', 'YES', 'YES'],
               ['age40', 'M', 'YES', 'YES', 'NO'],
               ['age50', 'M', 'YES', 'YES', 'YES'],
               ['age40', 'M', 'YES', 'YES', 'NO'],
               ['age40', 'M', 'YES', 'NO', 'NO'],
               ['age40', 'M', 'YES', 'NO', 'NO'],
               ['age40', 'M', 'YES', 'YES', 'NO'],
               ['age50', 'M', 'YES', 'NO', 'NO'],
               ['age40', 'M', 'NO', 'NO', 'NO'],
               ['age30', 'M', 'NO', 'YES', 'NO'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age40', 'M', 'YES', 'NO', 'YES'],
               ['age30', 'M', 'YES', 'NO', 'NO'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age50', 'F', 'NO', 'NO', 'YES'],
               ['age50', 'M', 'NO', 'NO', 'YES'],
               ['age40', 'F', 'NO', 'NO', 'NO'],
               ['age30', 'M', 'YES', 'YES', 'NO'],
               ['age40', 'M', 'NO', 'NO', 'YES'],
               ['age30', 'M', 'NO', 'YES', 'YES'],
               ['age40', 'M', 'YES', 'YES', 'YES'],
               ['age40', 'M', 'YES', 'NO', 'YES'],
               ['age40', 'M', 'NO', 'YES', 'YES'],
               ['age40', 'M', 'YES', 'YES', 'NO'],
               ['age50', 'M', 'YES', 'YES', 'YES'],
               ['age40', 'M', 'YES', 'YES', 'YES'],
               ['age50', 'M', 'NO', 'YES', 'NO'],
               ['age40', 'M', 'YES', 'NO', 'YES'],
               ['age30', 'M', 'NO', 'NO', 'NO'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age40', 'M', 'YES', 'YES', 'YES'],
               ['age30', 'M', 'YES', 'NO', 'NO'],
               ['age30', 'M', 'YES', 'YES', 'NO'],
               ['age50', 'M', 'YES', 'YES', 'YES'],
               ['age40', 'M', 'NO', 'NO', 'YES'],
               ['age50', 'M', 'YES', 'NO', 'YES'],
               ['age50', 'F', 'NO', 'NO', 'YES'],
               ['age50', 'F', 'NO', 'NO', 'YES'],
               ['age50', 'F', 'NO', 'NO', 'YES'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age40', 'F', 'NO', 'NO', 'NO'],
               ['age30', 'M', 'YES', 'YES', 'NO'],
               ['age50', 'M', 'YES', 'NO', 'NO'],
               ['age50', 'M', 'YES', 'YES', 'NO'],
               ['age50', 'F', 'NO', 'YES', 'NO'],
               ['age30', 'F', 'YES', 'NO', 'NO'],
               ['age30', 'M', 'YES', 'YES', 'NO'],
               ['age40', 'M', 'NO', 'YES', 'NO'],
               ['age30', 'M', 'YES', 'NO', 'YES'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age30', 'M', 'NO', 'NO', 'NO'],
               ['age40', 'M', 'YES', 'NO', 'YES'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age40', 'M', 'YES', 'NO', 'YES'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age30', 'M', 'YES', 'YES', 'NO'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age50', 'F', 'NO', 'NO', 'NO'],
               ['age40', 'M', 'YES', 'YES', 'NO'],
               ['age50', 'F', 'NO', 'NO', 'NO'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age30', 'F', 'YES', 'YES', 'NO'],
               ['age50', 'M', 'NO', 'NO', 'NO'],
               ['age50', 'M', 'YES', 'NO', 'NO'],
               ['age40', 'M', 'YES', 'YES', 'NO'],
               ['age50', 'F', 'NO', 'NO', 'NO'],
               ['age50', 'F', 'NO', 'YES', 'NO'],
               ['age50', 'F', 'YES', 'NO', 'YES'],
               ['age30', 'F', 'NO', 'NO', 'YES'],
               ['age30', 'M', 'NO', 'NO', 'YES'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age40', 'M', 'NO', 'YES', 'YES'],
               ['age40', 'M', 'YES', 'YES', 'NO'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age40', 'F', 'YES', 'NO', 'YES'],
               ['age50', 'M', 'YES', 'YES', 'NO'],
               ['age30', 'M', 'YES', 'NO', 'YES'],
               ['age40', 'M', 'YES', 'NO', 'NO'],
               ['age40', 'F', 'NO', 'NO', 'NO'],
               ['age40', 'F', 'NO', 'NO', 'NO'],
               ['age40', 'M', 'NO', 'NO', 'YES'],
               ['age40', 'F', 'NO', 'NO', 'NO'],
               ['age50', 'M', 'NO', 'NO', 'YES'],
               ['age50', 'F', 'NO', 'NO', 'NO'],
               ['age40', 'F', 'NO', 'NO', 'NO'],
               ['age30', 'F', 'YES', 'YES', 'NO'],
               ['age30', 'M', 'YES', 'YES', 'NO'],
               ['age30', 'F', 'NO', 'NO', 'YES'],
               ['age40', 'F', 'NO', 'NO', 'YES'],
               ['age50', 'F', 'NO', 'NO', 'YES'],
               ['age50', 'M', 'YES', 'NO', 'NO'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age30', 'M', 'NO', 'NO', 'YES'],
               ['age40', 'F', 'NO', 'NO', 'NO'],
               ['age40', 'M', 'YES', 'NO', 'NO'],
               ['age30', 'M', 'YES', 'NO', 'YES'],
               ['age50', 'F', 'NO', 'NO', 'YES'],
               ['age30', 'M', 'YES', 'NO', 'NO'],
               ['age50', 'F', 'NO', 'NO', 'NO'],
               ['age40', 'M', 'YES', 'NO', 'NO'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age30', 'M', 'YES', 'YES', 'NO'],
               ['age30', 'M', 'YES', 'NO', 'YES'],
               ['age40', 'F', 'NO', 'NO', 'NO'],
               ['age30', 'F', 'NO', 'NO', 'YES'],
               ['age40', 'F', 'NO', 'NO', 'NO'],
               ['age40', 'M', 'YES', 'NO', 'NO'],
               ['age30', 'F', 'YES', 'NO', 'NO'],
               ['age30', 'M', 'NO', 'NO', 'NO'],
               ['age30', 'M', 'YES', 'NO', 'YES'],
               ['age50', 'M', 'NO', 'NO', 'NO'],
               ['age50', 'M', 'YES', 'YES', 'YES'],
               ['age30', 'M', 'NO', 'YES', 'NO'],
               ['age50', 'M', 'YES', 'NO', 'NO'],
               ['age40', 'F', 'NO', 'NO', 'YES'],
               ['age50', 'F', 'NO', 'NO', 'NO'],
               ['age40', 'F', 'NO', 'NO', 'NO'],
               ['age30', 'F', 'YES', 'NO', 'NO'],
               ['age30', 'F', 'NO', 'YES', 'NO'],
               ['age50', 'F', 'NO', 'NO', 'NO'],
               ['age50', 'M', 'YES', 'YES', 'YES'],
               ['age40', 'F', 'NO', 'NO', 'NO'],
               ['age40', 'F', 'NO', 'NO', 'YES'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age40', 'M', 'NO', 'YES', 'YES'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age40', 'M', 'YES', 'YES', 'YES'],
               ['age50', 'M', 'NO', 'YES', 'YES'],
               ['age40', 'M', 'YES', 'NO', 'YES'],
               ['age50', 'F', 'NO', 'NO', 'YES'],
               ['age40', 'F', 'NO', 'NO', 'NO'],
               ['age40', 'F', 'NO', 'NO', 'NO'],
               ['age30', 'M', 'YES', 'YES', 'NO'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age30', 'M', 'NO', 'NO', 'NO'],
               ['age30', 'M', 'YES', 'YES', 'NO'],
               ['age30', 'F', 'YES', 'NO', 'NO'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age30', 'F', 'YES', 'NO', 'NO'],
               ['age50', 'M', 'YES', 'NO', 'NO'],
               ['age30', 'M', 'YES', 'YES', 'YES'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age40', 'M', 'YES', 'YES', 'NO'],
               ['age40', 'F', 'YES', 'NO', 'NO'],
               ['age40', 'M', 'YES', 'NO', 'NO'],
               ['age40', 'F', 'YES', 'NO', 'NO'],
               ['age40', 'M', 'YES', 'YES', 'NO'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age40', 'F', 'NO', 'NO', 'NO'],
               ['age30', 'M', 'YES', 'NO', 'NO'],
               ['age50', 'F', 'NO', 'NO', 'YES'],
               ['age50', 'M', 'YES', 'NO', 'NO'],
               ['age40', 'M', 'YES', 'YES', 'YES'],
               ['age30', 'M', 'YES', 'YES', 'NO'],
               ['age40', 'F', 'NO', 'NO', 'NO'],
               ['age40', 'M', 'YES', 'NO', 'NO'],
               ['age40', 'F', 'NO', 'NO', 'NO'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age30', 'M', 'NO', 'NO', 'NO'],
               ['age40', 'M', 'YES', 'YES', 'NO'],
               ['age50', 'M', 'YES', 'YES', 'YES'],
               ['age30', 'F', 'YES', 'YES', 'NO'],
               ['age50', 'M', 'YES', 'NO', 'NO'],
               ['age40', 'F', 'NO', 'NO', 'NO'],
               ['age40', 'M', 'YES', 'NO', 'NO'],
               ['age50', 'M', 'YES', 'YES', 'YES'],
               ['age40', 'M', 'YES', 'NO', 'NO'],
               ['age40', 'F', 'NO', 'NO', 'NO'],
               ['age50', 'F', 'NO', 'NO', 'NO'],
               ['age50', 'F', 'NO', 'NO', 'NO'],
               ['age30', 'F', 'YES', 'NO', 'NO'],
               ['age30', 'M', 'NO', 'YES', 'YES'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age40', 'F', 'NO', 'NO', 'NO'],
               ['age40', 'F', 'NO', 'NO', 'NO'],
               ['age40', 'F', 'NO', 'NO', 'NO'],
               ['age40', 'F', 'YES', 'NO', 'NO'],
               ['age30', 'M', 'YES', 'YES', 'NO'],
               ['age40', 'M', 'YES', 'YES', 'NO'],
               ['age30', 'F', 'YES', 'NO', 'NO'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age30', 'M', 'YES', 'YES', 'YES'],
               ['age30', 'M', 'YES', 'NO', 'NO'],
               ['age30', 'F', 'YES', 'NO', 'NO'],
               ['age30', 'F', 'YES', 'NO', 'NO'],
               ['age30', 'M', 'YES', 'YES', 'NO'],
               ['age40', 'M', 'YES', 'NO', 'NO'],
               ['age40', 'M', 'YES', 'NO', 'NO'],
               ['age40', 'M', 'NO', 'YES', 'NO'],
               ['age50', 'M', 'YES', 'YES', 'NO'],
               ['age50', 'F', 'NO', 'NO', 'NO'],
               ['age40', 'M', 'YES', 'YES', 'NO'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age40', 'M', 'YES', 'YES', 'NO'],
               ['age50', 'M', 'YES', 'NO', 'YES'],
               ['age40', 'F', 'NO', 'NO', 'NO'],
               ['age50', 'M', 'YES', 'NO', 'NO'],
               ['age50', 'F', 'NO', 'NO', 'NO'],
               ['age40', 'M', 'YES', 'YES', 'NO'],
               ['age50', 'F', 'NO', 'NO', 'YES'],
               ['age50', 'M', 'YES', 'NO', 'YES'],
               ['age50', 'M', 'YES', 'NO', 'NO'],
               ['age40', 'F', 'NO', 'NO', 'NO'],
               ['age40', 'M', 'NO', 'NO', 'NO'],
               ['age50', 'M', 'NO', 'NO', 'YES'],
               ['age50', 'F', 'NO', 'NO', 'YES'],
               ['age40', 'M', 'YES', 'YES', 'YES'],
               ['age30', 'M', 'YES', 'YES', 'NO'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age30', 'M', 'YES', 'YES', 'NO'],
               ['age40', 'M', 'YES', 'YES', 'NO'],
               ['age50', 'F', 'NO', 'NO', 'YES'],
               ['age50', 'F', 'NO', 'NO', 'NO'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age50', 'M', 'NO', 'NO', 'NO'],
               ['age30', 'M', 'NO', 'NO', 'NO'],
               ['age40', 'M', 'YES', 'NO', 'NO'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age30', 'M', 'YES', 'YES', 'NO'],
               ['age30', 'M', 'NO', 'NO', 'NO'],
               ['age50', 'F', 'NO', 'NO', 'NO'],
               ['age50', 'M', 'YES', 'YES', 'NO'],
               ['age40', 'F', 'NO', 'NO', 'NO'],
               ['age40', 'F', 'NO', 'NO', 'NO'],
               ['age50', 'M', 'NO', 'YES', 'YES'],
               ['age40', 'F', 'NO', 'NO', 'NO'],
               ['age30', 'M', 'NO', 'YES', 'YES'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age40', 'F', 'NO', 'NO', 'NO'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age50', 'M', 'NO', 'NO', 'YES'],
               ['age30', 'M', 'YES', 'YES', 'NO'],
               ['age40', 'M', 'YES', 'YES', 'NO'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age40', 'M', 'YES', 'YES', 'NO'],
               ['age40', 'M', 'YES', 'YES', 'YES'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age50', 'F', 'NO', 'NO', 'YES'],
               ['age40', 'F', 'NO', 'NO', 'NO'],
               ['age50', 'F', 'NO', 'NO', 'YES'],
               ['age30', 'F', 'YES', 'NO', 'NO'],
               ['age40', 'F', 'NO', 'NO', 'NO'],
               ['age40', 'M', 'YES', 'YES', 'NO'],
               ['age40', 'F', 'NO', 'NO', 'YES'],
               ['age30', 'M', 'YES', 'YES', 'NO'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age30', 'M', 'YES', 'YES', 'NO'],
               ['age30', 'M', 'YES', 'NO', 'YES'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age30', 'M', 'YES', 'YES', 'NO'],
               ['age40', 'M', 'NO', 'NO', 'NO'],
               ['age50', 'M', 'YES', 'NO', 'NO'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age40', 'F', 'YES', 'NO', 'NO'],
               ['age40', 'F', 'NO', 'NO', 'NO'],
               ['age50', 'M', 'YES', 'YES', 'NO'],
               ['age40', 'F', 'NO', 'NO', 'NO'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age50', 'M', 'YES', 'NO', 'YES'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age50', 'F', 'NO', 'NO', 'NO'],
               ['age30', 'M', 'YES', 'YES', 'NO'],
               ['age40', 'F', 'NO', 'NO', 'NO'],
               ['age40', 'F', 'NO', 'NO', 'NO'],
               ['age40', 'F', 'NO', 'NO', 'NO'],
               ['age50', 'F', 'NO', 'NO', 'NO'],
               ['age50', 'M', 'YES', 'NO', 'YES'],
               ['age40', 'M', 'NO', 'NO', 'NO'],
               ['age40', 'M', 'YES', 'YES', 'NO'],
               ['age40', 'M', 'YES', 'YES', 'NO'],
               ['age40', 'M', 'NO', 'NO', 'NO'],
               ['age40', 'M', 'NO', 'YES', 'NO'],
               ['age40', 'M', 'YES', 'YES', 'YES'],
               ['age40', 'F', 'NO', 'NO', 'NO'],
               ['age30', 'M', 'YES', 'NO', 'NO'],
               ['age30', 'M', 'YES', 'NO', 'NO'],
               ['age30', 'M', 'YES', 'YES', 'NO'],
               ['age50', 'F', 'NO', 'NO', 'NO'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age40', 'M', 'YES', 'YES', 'NO'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age30', 'M', 'NO', 'YES', 'NO'],
               ['age40', 'F', 'NO', 'NO', 'YES'],
               ['age30', 'M', 'YES', 'YES', 'NO'],
               ['age50', 'M', 'YES', 'NO', 'NO'],
               ['age30', 'M', 'YES', 'NO', 'NO'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age40', 'M', 'YES', 'YES', 'NO'],
               ['age40', 'F', 'NO', 'NO', 'NO'],
               ['age40', 'M', 'YES', 'NO', 'NO'],
               ['age50', 'F', 'NO', 'NO', 'NO'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age30', 'M', 'YES', 'YES', 'NO'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age40', 'M', 'YES', 'YES', 'NO'],
               ['age40', 'F', 'NO', 'NO', 'NO'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age40', 'F', 'NO', 'NO', 'NO'],
               ['age50', 'F', 'NO', 'NO', 'YES'],
               ['age40', 'M', 'YES', 'YES', 'NO'],
               ['age40', 'F', 'NO', 'NO', 'NO'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age30', 'M', 'NO', 'YES', 'YES'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age40', 'M', 'YES', 'NO', 'YES'],
               ['age30', 'F', 'YES', 'NO', 'NO'],
               ['age40', 'M', 'YES', 'YES', 'YES'],
               ['age40', 'F', 'NO', 'NO', 'NO'],
               ['age50', 'M', 'NO', 'NO', 'NO'],
               ['age50', 'M', 'YES', 'YES', 'NO'],
               ['age50', 'M', 'NO', 'NO', 'NO'],
               ['age50', 'F', 'NO', 'NO', 'YES'],
               ['age40', 'M', 'YES', 'YES', 'YES'],
               ['age40', 'M', 'YES', 'NO', 'YES'],
               ['age40', 'F', 'NO', 'NO', 'NO'],
               ['age50', 'M', 'YES', 'YES', 'NO'],
               ['age30', 'F', 'YES', 'NO', 'NO'],
               ['age50', 'F', 'NO', 'NO', 'YES'],
               ['age40', 'F', 'NO', 'NO', 'NO'],
               ['age40', 'M', 'YES', 'NO', 'NO'],
               ['age30', 'M', 'YES', 'YES', 'NO'],
               ['age30', 'M', 'YES', 'YES', 'YES'],
               ['age30', 'F', 'YES', 'NO', 'NO'],
               ['age30', 'F', 'NO', 'NO', 'YES'],
               ['age50', 'F', 'NO', 'NO', 'YES'],
               ['age30', 'M', 'YES', 'YES', 'NO'],
               ['age30', 'M', 'NO', 'NO', 'NO'],
               ['age40', 'F', 'YES', 'NO', 'YES'],
               ['age40', 'F', 'NO', 'NO', 'NO'],
               ['age50', 'F', 'NO', 'NO', 'NO'],
               ['age40', 'F', 'YES', 'NO', 'NO'],
               ['age30', 'M', 'YES', 'NO', 'NO'],
               ['age30', 'M', 'YES', 'YES', 'NO'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age40', 'M', 'YES', 'YES', 'NO'],
               ['age40', 'M', 'YES', 'NO', 'NO'],
               ['age50', 'M', 'YES', 'YES', 'NO'],
               ['age50', 'F', 'NO', 'NO', 'NO'],
               ['age30', 'M', 'YES', 'NO', 'YES'],
               ['age50', 'M', 'NO', 'NO', 'NO'],
               ['age30', 'M', 'YES', 'YES', 'YES'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age30', 'M', 'YES', 'NO', 'NO'],
               ['age50', 'M', 'NO', 'NO', 'YES'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age40', 'M', 'NO', 'NO', 'NO'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age40', 'F', 'NO', 'NO', 'NO'],
               ['age40', 'F', 'NO', 'NO', 'NO'],
               ['age50', 'F', 'NO', 'NO', 'NO'],
               ['age50', 'M', 'YES', 'NO', 'YES'],
               ['age50', 'F', 'NO', 'NO', 'NO'],
               ['age50', 'F', 'NO', 'NO', 'NO'],
               ['age40', 'M', 'YES', 'YES', 'YES'],
               ['age30', 'M', 'YES', 'YES', 'NO'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age40', 'F', 'NO', 'NO', 'YES'],
               ['age40', 'M', 'YES', 'YES', 'NO'],
               ['age30', 'M', 'YES', 'YES', 'YES'],
               ['age30', 'M', 'YES', 'YES', 'YES'],
               ['age40', 'M', 'YES', 'YES', 'YES'],
               ['age50', 'F', 'NO', 'NO', 'YES'],
               ['age30', 'F', 'NO', 'NO', 'NO'],
               ['age40', 'M', 'NO', 'NO', 'YES'],
               ['age40', 'M', 'YES', 'NO', 'NO'],
               ['age40', 'M', 'YES', 'NO', 'NO'],
               ['age40', 'M', 'NO', 'YES', 'NO'],
               ['age40', 'M', 'YES', 'YES', 'NO'],
               ['age50', 'M', 'YES', 'YES', 'YES'],
               ['age40', 'M', 'YES', 'YES', 'NO'],
               ['age40', 'M', 'YES', 'YES', 'YES'],
               ['age40', 'M', 'YES', 'YES', 'NO'],
               ['age40', 'M', 'NO', 'NO', 'NO'],
               ['age40', 'M', 'YES', 'NO', 'NO'],
               ['age50', 'M', 'YES', 'NO', 'YES'],
               ['age40', 'M', 'YES', 'NO', 'NO'],
               ['age50', 'M', 'YES', 'YES', 'YES'],
               ['age40', 'F', 'NO', 'NO', 'NO'],
               ['age30', 'F', 'YES', 'NO', 'YES']]
    labels = ['AGE', 'GENDER_yn', 'DRINK_yn', 'SMOKE_yn', 'FATLIVER_yn']
    return dataSet, labels


def calcShannonEnt(dataSet):  # 분할 전 엔트로피 구하기
    numEntries = len(dataSet)  # row의 개수 5
    labelCounts = {}
    for feaVec in dataSet:
        currentLabel = feaVec[-1]
        if currentLabel not in labelCounts:
            labelCounts[currentLabel] = 0
        labelCounts[currentLabel] += 1  # labelCounts={'yes':2,'no':3}
    shannonEnt = 0.0
    for key in labelCounts:
        prob = float(labelCounts[key]) / numEntries
        shannonEnt -= prob * log(prob, 2)  # yes:0.52877, no:0.97095
    return shannonEnt


def splitDataSet(dataSet, axis, value):  # 각 row에서 해당 변수제외하고 나머지 값들의 리스트
    retDataSet = []
    for featVec in dataSet:
        if featVec[axis] == value:
            reducedFeatVec = featVec[:axis]
            reducedFeatVec.extend(featVec[axis + 1:])
            retDataSet.append(reducedFeatVec)
    return retDataSet


def chooseBestFeatureToSplit(dataSet):  # 어떤 속성이 정보이득이 가장큰지
    numFeatures = len(dataSet[0]) - 1  # 한 row가 갖는 속성의 개수-1
    baseEntropy = calcShannonEnt(dataSet)  # 분할 전 엔트로피
    bestInfoGain = 0.0
    bestFeature = -1
    for i in range(numFeatures):  # dataSet의 target변수 제외 속성 리스트
        # [1, 1, 1, 0, 0] [1, 1, 0, 1, 1]
        featList = [example[i] for example in dataSet]
        uniqueVals = set(featList)  # set() : 중복제거된 요소들 {0, 1}
        newEntropy = 0.0
        for value in uniqueVals:
            subDataSet = splitDataSet(dataSet, i, value)
            prob = len(subDataSet) / float(len(dataSet))
            newEntropy += prob * calcShannonEnt(subDataSet)  # 분할 후 엔트로피
        infoGain = baseEntropy - newEntropy  # 정보이득
        if infoGain > bestInfoGain:
            bestInfoGain = infoGain
            bestFeature = i
    return bestFeature  # 가장 큰 정보이득을 갖는 속성


def majorityCnt(classList):  # 가장 많은 빈도수의 값을 리턴해줌
    classCount = {}
    for vote in classList:  # ['yes','yes','no','no','no']
        if vote not in classCount.keys():
            classCount[vote] = 0
        classCount[vote] += 1  # classCount={'yes':2,'no':3}
    sortedClassCount = sorted(classCount.items(), key=operator.itemgetter(1), reverse=True)
    return sortedClassCount[0][0]


def createTree(dataSet, labels):
    classList = [example[-1] for example in dataSet]  # ['yes','yes','no','no','no']
    # 종료조건1 : 모두 'yes'이거나 모두 'no'이면 종료하고 그 항목 리턴
    if classList.count(classList[0]) == len(classList):
        return classList[0]
    # 종료조건2 : [1,0,'yes']->[1,0]->[1] 데이터셋의 변수가 1개가 됐을 때 majorityCnt리턴
    if len(dataSet[0]) == 1:
        return majorityCnt(classList)
    bestFeat = chooseBestFeatureToSplit(dataSet)  # 어떤 속성이 정보이득이 가장 큰지
    bestFeatLabel = labels[bestFeat]
    myTree = {bestFeatLabel: {}}
    del (labels[bestFeat])
    featValues = [example[bestFeat] for example in dataSet]
    uniqueVals = set(featValues)
    for value in uniqueVals:
        subLabels = labels[:]
        myTree[bestFeatLabel][value] = createTree(splitDataSet(dataSet,
                                                               bestFeat, value), subLabels)
    return myTree


def main():
    data, label = createDataSet()
    t1 = time.clock()
    myTree = createTree(data, label)
    t2 = time.clock()
    print(myTree)
    print('execute for ', t2 - t1)  # 실행시간 재는거


if __name__ == '__main__':
    main()